MakefileのmacOS対応
openmps/openmps pull request #21
Opened 2019-08-07 14:48 UTC by likr

macOS（Darwin）の場合に `-Xpreprocessor` フラグを追加しました。
macOS 10.14.5とUbuntu 19.04で動作確認しました。

2019-08-20 01:52 UTC, LWisteria requested changes
@likr PRありがとうございます。macOSを私は持っていないので有効性を確認はできないんですが、ともあれ保守性がちょっと良くないので修正をお願いできますか

2019-08-20 01:52 UTC, LWisteria commented on src/OpenMps/Makefile
> +	CFLAGS   = -g -MMD -MP -O3 -std=c++14 -stdlib=libc++ -Wall -Wextra -Werror -Wfatal-errors -Wno-unknown-pragmas -march=native -mtune=native -Xpreprocessor -fopenmp
完全に分離するのではなく、macOSのときにはOpenMP周りだけの設定「-Xpreprocessorを追加した -fopenmp」だけしてもらえないでしょうか

```
CFLAGS = ..... mtune=native
if macOS
    CFLAGS += -Xpreprocessor
CFLGAS += -fopenmp
```

みたいな感じで

2019-08-27 08:45 UTC, likr commented
ありがとうございます。ご指摘の部分修正しました。

2019-08-30 02:26 UTC, LWisteria approved these changes
LGTM

2019-08-30 02:26 UTC, merged