GoogleTestのVSプロジェクト追加
openmps/openmps pull request #22
Opened 2019-08-09 08:10 UTC by maru10t

testディレクトリ以下のテストケースをビルド・実行できるプロジェクトファイル追加する。

* 動作バージョン
   * Visual Studio Community 2019 (Version 16.1.3)
   * Boost 1.7

* プロジェクトを設定した手順
     * 新規ソリューション作成で Google Test を選択
     * pch.hpp, pch.cpp を削除
     * プロジェクトのプロパティでプリコンパイル済みヘッダを使用しない設定に変更
     * 追加のインクルードディレクトリ に $(MSBuildThisFiledDirectory)..\..\viennacl追加

* packagesディレクトリを含めていない件
      *  ビルドの際に「NuGetパッケージの復元」が動作して適切にgoogletestライブラリが配置されることを確認

2019-08-20 01:38 UTC, LWisteria requested changes
レビューしました！

2019-08-20 01:38 UTC, LWisteria commented on src/OpenMps/test/packages.config
> +  <package id="Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn" version="1.8.1" targetFramework="native" />
gitsubmoduleでsrc直下にgoogletestが既にいるので、これは重複していて無駄じゃないでしょうか？

2019-08-20 01:38 UTC, LWisteria commented on src/OpenMps/test/test.sln
> +﻿
slnをここにおくようになるのであれば、Makefileの単体試験の設定もtestディレクトリに移したほうが良さそうですね

2019-08-20 01:48 UTC, maru10t commented on src/OpenMps/test/packages.config
> +  <package id="Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn" version="1.8.1" targetFramework="native" />
githubリポジトリにあるgoogletestには、VS用のファイル群(プロジェクトファイル等)が最近含まれなくなったようです。
ライブラリのビルド・リンクまでを設定するのが時間喰いそうだったため、packages.configを置いてVSにパッケージ設定を任せこちらの方法を採用しました。

2019-08-20 01:51 UTC, maru10t commented on src/OpenMps/test/test.sln
> +﻿
確かにそうですね。統一するよう修正します。

2019-08-20 02:16 UTC, LWisteria commented on src/OpenMps/test/packages.config
> +  <package id="Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn" version="1.8.1" targetFramework="native" />
googletestはcmakeなのでビルドとか普通にできそうですけど、それがダメだったってことでしょうか？

2019-08-20 02:19 UTC, maru10t commented on src/OpenMps/test/packages.config
> +  <package id="Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn" version="1.8.1" targetFramework="native" />
cmakeがvsに対応してるのを知りませんでした。試してみます！

2019-08-22 02:17 UTC, maru10t commented
githubリポジトリのgoogletest, cmakeでvs用プロジェクト生成
Releseビルドして`gtest.lib, gtest_main.lib`を生成した。

`googletest/libs/Release`を追加ライブラリディレクトリ、`googletest/googletest/include`を追加インクルードディレクトリにしてビルド

↓のような、重複定義のエラーが起きる。
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	LNK2005	_Getcvt は既に msvcprtd.lib(MSVCP140D.dll) で定義されています。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(xwctomb.obj)	1	
```

ライブラリとtestプログラムで、Cのランタイムが不一致である問題であると思われる。対処中。

2019-08-22 02:51 UTC, maru10t commented
cmake生成のプロジェクトファイルのビルド設定を見て、設定を一致させてみた
* 優先するビルドツールアーキテクチャ: x64
* デバッグライブラリの使用: いいえ
* 詳細設定 > コンパイル言語の選択: C++コードとしてコンパイル (/TP)
にしてみた。

boostの mt-s (multithread static) が要求されるようになった。こいつをコンパイルして再度試す。 
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	LNK1104	ファイル 'libboost_serialization-vc142-mt-s-x64-1_70.lib' を開くことができません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\LINK	1	
```

2019-08-22 04:12 UTC, maru10t commented
* testプロジェクト側もReleaseビルドにしてみた -> 同様のエラー


* こういうエラー(下記)が見られるため、gtest.libにC++ランタイムが含まれてしまっている？(わかってない)
* googletestのcmake設定を書き替えるのは避けたいので、testプロジェクト側で引き続きリンク設定を試行錯誤してみるかなあ...。
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	LNK2005	"public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void)" (??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ) は既に gtest.lib(gtest-all.obj) で定義されています。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\msvcprt.lib(MSVCP140.dll)	1	
エラー	LNK2005	"public: char __cdecl std::basic_ios<char,struct std::char_traits<char> >::widen(char)const " (?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADD@Z) は既に gtest.lib(gtest-all.obj) で定義されています。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\msvcprt.lib(MSVCP140.dll)	1	
エラー	LNK2005	"public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) は既に gtest.lib(gtest-all.obj) で定義されています。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\msvcprt.lib(MSVCP140.dll)	1	
```

2019-08-22 04:16 UTC, maru10t commented
* testプロジェクト側をReleaseでリビルドしたら、ランタイム不一致エラーは消えて、以下のエラーに。
(はるか昔の記憶に、ライブラリのDebug/Release,  リンク側のDebug/Releaseは揃えるという教訓を得たような気がするが、思い出すのに時間がかかった・・・)
* Static, Dynamicの設定いじれば解決できそう

```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\gtest.lib(gtest-all.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(locale0.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(cerr.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(locale.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(iosptrs.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(xlock.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(wlocale.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(xlocale.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(xdateord.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(winapisupp.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(StlCompareStringA.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(winapinls.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(StlCompareStringW.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(StlLCMapStringW.obj)	1	
エラー	LNK2038	'RuntimeLibrary' の不一致が検出されました。値 'MT_StaticRelease' が MD_DynamicRelease の値 'test_ComputerConstructor.obj' と一致しません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\libcpmt.lib(StlLCMapStringA.obj)	1	
```

2019-08-22 04:23 UTC, maru10t commented
* ランタイムライブラリ: マルチスレッド(MT)
にしたら、再度 boost要求のエラー。先ほどはこの設定のON/OFFを気づかないうちに行っていたらしい。やはりboostは マルチスレッド static版のビルドが必要か。

```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	LNK1104	ファイル 'libboost_serialization-vc142-mt-s-x64-1_70.lib' を開くことができません。	test	C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\LINK	1	
```

2019-08-22 05:10 UTC, maru10t commented
* `b2.exe install --build-type=complete`でフルでビルドした
* test側のビルドに成功. Debug/Releaseともに。

2019-08-22 05:16 UTC, maru10t commented on src/OpenMps/test/packages.config
> +  <package id="Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn" version="1.8.1" targetFramework="native" />
cmakeを使用するよう対応しました

2019-08-22 05:18 UTC, maru10t commented
@LWisteria cmakeの件、Makefile分離の件 修正しました！

2019-08-22 09:25 UTC, LWisteria requested changes
@maru10t レビューしました！

2019-08-22 09:25 UTC, LWisteria commented on src/OpenMps/test/test.vcxproj
> +      <AdditionalIncludeDirectories>$(MSBuildThisFiledDirectory)..\..\googletest\googletest\include;$(MSBuildThisFiledDirectory)..\..\viennacl;%(AdditionalIncludeDirectories)</AdditionalIncludeDirect
$(MSBuildThisFiledDirectory)だとターゲットの場所によって変わってしまうので、本体側と同じく$(SolutionDir)を使って指定したほうがいいと思うんですが、どうでしょう？

2019-08-22 09:25 UTC, LWisteria commented on src/OpenMps/test/packages.config
> +  <package id="Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn" version="1.8.1" targetFramework="native" />
となると、このpackage設定はもう消しても良いですね？

2019-08-22 09:25 UTC, LWisteria commented on src/OpenMps/test/Makefile
> +INCLUDE  = -isystem ../../viennacl
これ、include指定漏れてません？

2019-08-22 09:25 UTC, LWisteria commented on src/OpenMps/test/test.vcxproj
> +      <AdditionalLibraryDirectories>$(MSBuildThisFiledDirectory)..\..\googletest\lib\Release;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
#18 でboostもNuGetを使うように変更されているので、libもその位置packages/...に設定したほうがよいですね。

2019-08-30 00:49 UTC, maru10t commented
これまでNuGetでないboostでコンパイルしていたので、NuGet Boost を手元で確認中

2019-08-30 01:08 UTC, maru10t commented on src/OpenMps/test/test.vcxproj
> +      <AdditionalIncludeDirectories>$(MSBuildThisFiledDirectory)..\..\googletest\googletest\include;$(MSBuildThisFiledDirectory)..\..\viennacl;%(AdditionalIncludeDirectories)</AdditionalIncludeDirect
確かにそう思います。そのように修正しました。

2019-08-30 01:09 UTC, maru10t commented on src/OpenMps/test/test.vcxproj
> +      <AdditionalLibraryDirectories>$(MSBuildThisFiledDirectory)..\..\googletest\lib\Release;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
はい、設定しました。

2019-08-30 01:10 UTC, maru10t commented
* 分離したmakefileでのビルド確認中

2019-08-30 01:34 UTC, maru10t commented on src/OpenMps/test/Makefile
> +INCLUDE  = -isystem ../../viennacl
TESTINCLUDEの方にgoogletest等を指定していました。
変数の無駄が多かったのでリファクタリングしました。

2019-08-30 01:36 UTC, maru10t commented
@LWisteria 指摘の点修正しました！

2019-08-30 02:33 UTC, LWisteria approved these changes
LGTM

2019-08-30 02:33 UTC, merged