WIP: 粒子数密度の計算のテスト
openmps/openmps pull request #26
Opened 2019-09-06 08:03 UTC by maru10t

近傍粒子の検索、粒子数密度の計算のテストコードを追加する。

2019-09-06 08:03 UTC, maru10t commented
テスト内容書いた。整理中。

* 距離関数R
      * 距離の公理的なやつ
* 近傍粒子探索が満たすべき性質
      * 近接している粒子が互いを近傍粒子と認識している
      * 自分自身は除外
* 手で見積もった粒子数密度との計算値の比較
      * 越塚さんの教科書からの値を参照

2019-09-17 01:57 UTC, maru10t commented
@LWisteria レビューお願いします

2019-09-17 03:01 UTC, LWisteria requested changes
@maru10t レビューしました

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/Computer.hpp
> +	friend class DensityTest;
粒子数密度は密度ではないので、名前を変えたほうがいいですね

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +	static constexpr int num_ps_x = 7;
psとは・・・？

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +			OpenMps::Computer<decltype(positionWall)&, decltype(positionWallPre)&> comp = OpenMps::CreateComputer(
これ、直接代入せずにわざわざ一時変数を挟んでいる理由ってなんででしたっけ？

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +		double Rv(const Vector& x1, const Vector& x2)
particleと関数名を分ける必要あります？（多重定義では何か問題が？

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +		// �_���ւ��ɂ��đΏ̂��H
同じ中で複数の条件を試験するのは単体試験としてはあまりよろしくないです。テストケースを3つに分割したほうが良いと思います。

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +	// �����v�Z�͋����̊�{�I�����𖞑����邩�H
そもそもとして「期待する（ユークリッド）距離になっているか」を確認するのも必要だと思います。

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +	    // i: ��ɑ��݂��闱�q�𑖍�
indent?

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +					neigh_symm &= j_has_i;
ここでassertしてしまってもよいのではないでしょうか

2019-09-17 03:01 UTC, LWisteria commented on src/OpenMps/test/test_ComputerDensity.cpp
> +			}
こっちもここでassertできますね

2019-09-17 03:02 UTC, maru10t commented
@LWisteria レビューありがとうございます。確認して修正行います。

2019-09-17 03:41 UTC, maru10t commented on src/OpenMps/Computer.hpp
> +	friend class DensityTest;
NumberDensityに変更しました

2019-09-17 03:42 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +	static constexpr int num_ps_x = 7;
思い出せませんでした！ので num_xなどと修正しました

2019-09-17 03:43 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +			OpenMps::Computer<decltype(positionWall)&, decltype(positionWallPre)&> comp = OpenMps::CreateComputer(
たしかに一時変数いらないと思いました。削除しました。

2019-09-17 03:44 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +		double Rv(const Vector& x1, const Vector& x2)
ないと思います。多重定義に変更しました。
(前回試した時に多重定義に失敗したので分けたが、改めて試したら上手くいった...。)

2019-09-17 03:44 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +		// �_���ւ��ɂ��đΏ̂��H
3つに分割しました。

2019-09-17 03:45 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +	// �����v�Z�͋����̊�{�I�����𖞑����邩�H
距離の値自体のテストも追加しました

2019-09-17 03:47 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +					neigh_symm &= j_has_i;
たしかに。そのようにしました。

2019-09-17 03:47 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +			}
assertしました

2019-09-17 03:54 UTC, maru10t commented on src/OpenMps/test/test_ComputerDensity.cpp
> +	    // i: ��ɑ��݂��闱�q�𑖍�
修正しました。

2019-09-17 03:56 UTC, maru10t commented
@LWisteria 指摘の点修正しました

2019-09-17 06:37 UTC, LWisteria approved these changes
LGTM

2019-09-17 06:37 UTC, merged