WIP: computeExplicitForces() のテスト追加
openmps/openmps pull request #28
Opened 2019-10-03 03:14 UTC by maru10t

* computeExplicitForces() は 重力 と 粘性応力 を計算して、加速度に応じて粒子速度・位置を更新する関数である。
* 初期速度分布を 2次関数、三角関数として 数値解と解析解の相対誤差をテストする。

2019-10-03 03:15 UTC, maru10t commented
多項式 ax^2+bxy+cy^2+d と 三角関数 a sin(p x) + b cos(q y) の二階微分を解析解と数値解を比較、相対誤差がtestAccuracy未満であるかをテスト

#### MPS_HSがOFFのとき
```
[ RUN      ] ExplicitForcesTest.ForceValuePolynomial
[       OK ] ExplicitForcesTest.ForceValuePolynomial (6 ms)
[ RUN      ] ExplicitForcesTest.ForceValueSinCos
[       OK ] ExplicitForcesTest.ForceValueSinCos (6 ms)
```

#### MPS_HSがONのとき

* 関数系によらず定数誤差であることがわかるので、高精度ラプラシアンの係数ミス等であるはず。
* 7x7粒子を配置して、中央粒子の点での微分値を評価しているので、境界の影響はないはず
 
```
[ RUN      ] ExplicitForcesTest.ForceValuePolynomial
Workspace\openmps\src\OpenMps\test\test_ComputerXXX.cpp(192): error: The difference between abs( (ax-ax_analy)/ax_analy ) and 0.0 is 1.1262105621960912, which exceeds testAccuracy, where
abs( (ax-ax_analy)/ax_analy ) evaluates to 1.1262105621960912,
0.0 evaluates to 0, and
testAccuracy evaluates to 0.001.
[  FAILED  ] ExplicitForcesTest.ForceValuePolynomial (5 ms)
[ RUN      ] ExplicitForcesTest.ForceValueSinCos
Workspace\openmps\src\OpenMps\test\test_ComputerXXX.cpp(257): error: The difference between abs( (ax-ax_analy)/ax_analy ) and 0.0 is 1.1262522566365114, which exceeds testAccuracy, where
abs( (ax-ax_analy)/ax_analy ) evaluates to 1.1262522566365114,
0.0 evaluates to 0, and
testAccuracy evaluates to 0.001.
[  FAILED  ] ExplicitForcesTest.ForceValueSinCos (7 ms)
```

2019-10-03 03:17 UTC, maru10t commented
TODO: 一点での比較であるので速度空間分布の比較を行うように変更する。

2019-10-03 05:43 UTC, maru10t commented
@LWisteria こちらレビューお願いします

2019-10-03 05:44 UTC, maru10t commented
MPS_HLを有効にすると係数合わない問題修正は別のPRに回します。

2019-10-08 00:05 UTC, LWisteria requested changes
@maru10t レビューしました

2019-10-08 00:05 UTC, LWisteria commented on src/OpenMps/test/test.vcxproj
> +    <ClCompile Include="test_ComputerXXX.cpp" />
なんかの修正漏れですか？

2019-10-08 00:05 UTC, LWisteria commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +	static constexpr int num_x = 13;
今気づきましたが、「個数」ならintではなくsize_tであるべきですね（他のところもそうですかね

2019-10-08 00:05 UTC, LWisteria commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +			for (int j = 0; j < num_z; ++j)
なのでループもintを使うべきではないです

2019-10-08 00:05 UTC, LWisteria commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +			for (int j = 0; j < num_z; ++j)
（正しい書き方はComputer.hppを見てください）

2019-10-08 00:05 UTC, LWisteria commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +			auto accNum = (v1 - v0) / dt_step;
const

2019-10-08 00:10 UTC, maru10t commented
@LWisteria レビューありがとうございます。修正着手します。

2019-10-08 00:24 UTC, LWisteria commented
あと、これも今気づいたので今書いておくのですが、x86とかWin32とか32bit向けのビルド設定が残ったままですね。
サポートする意味はまったくないので、ついでに設定を消しておいてほしいです（構成マネージャーから消せます）。

2019-10-08 00:33 UTC, maru10t commented on src/OpenMps/test/test.vcxproj
> +    <ClCompile Include="test_ComputerXXX.cpp" />
誤って追加したファイルでしたので除外しました。

2019-10-08 00:34 UTC, maru10t commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +	static constexpr int num_x = 13;
他のテストも含めてsize_tに定義・ループ処理を修正しました。

2019-10-08 00:34 UTC, maru10t commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +			for (int j = 0; j < num_z; ++j)
同上。

2019-10-08 00:35 UTC, maru10t commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +			auto accNum = (v1 - v0) / dt_step;
ぎゃーミスでした。付与しました。

2019-10-08 00:36 UTC, LWisteria commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +	static constexpr int num_x = 13;
あ、C++なのでstd::size_tです・・・

2019-10-08 00:51 UTC, maru10t commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +	static constexpr int num_x = 13;
ですね...。修正しました！

2019-10-08 00:52 UTC, maru10t commented
@LWisteria 修正しました。

2019-10-08 00:55 UTC, LWisteria requested changes
@maru10t レビューしました！

2019-10-08 00:55 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConstructor.cpp
> +#ifdef SIGNED_LOOP_COUNTER
試験コードでOpenMPを使う必要はないと思うので、符号なしに合わせたほうで書いちゃって良いと思います

2019-10-08 00:55 UTC, LWisteria commented on src/OpenMps/test/test.vcxproj
> -    <ProjectConfiguration Include="Debug|Win32">
あと、たぶんslnファイルの方にもx86が残ったままだと思います。保存漏れですかね？

2019-10-08 01:01 UTC, maru10t commented on src/OpenMps/test/test.vcxproj
> -    <ProjectConfiguration Include="Debug|Win32">
その通りでした。コミットに含めました。

2019-10-08 01:03 UTC, maru10t commented on src/OpenMps/test/test_ComputerConstructor.cpp
> +#ifdef SIGNED_LOOP_COUNTER
SIGNED LOOP削除しました。
今後もOpenMPの場合分け等は含めないようにしていきます。

2019-10-08 01:04 UTC, maru10t commented
@LWisteria 指摘の点、修正しました。

2019-10-08 01:10 UTC, LWisteria approved these changes
LGTM

2019-10-08 01:10 UTC, merged