WIP: CIでのテスト実行, MSBuild対応
openmps/openmps pull request #36
Opened 2019-11-20 00:49 UTC by maru10t

2019-11-20 00:52 UTC, maru10t commented
当然、MPS_HS が ON のため ラプラシアン不一致#30 に引っ掛かりCI 通らず。

2019-11-20 00:57 UTC, maru10t commented
msbuildはこちらを参考に組んでいる(2日前の記事)
https://qiita.com/y428_b/items/f8e0c598238d75f808b1

2019-11-20 02:21 UTC, maru10t commented
logが出ないしおかしいぞと思ってたら、
workflowに障害発生中らしい: https://www.githubstatus.com/
```

Incident on 2019-11-20 01:19 UTC
Subscribe
Update - We are investigating errors starting runs for Actions workflows.
Nov 20, 02:20 UTC
Update - We continue to investigate problems starting runs for Actions workflows.
Nov 20, 01:52 UTC
Investigating - We are investigating problems starting runs for Actions workflows.
Nov 20, 01:19 UTC

```

2019-11-20 02:28 UTC, LWisteria commented
HSの問題でCIが通らない問題は、試験を一時的に無効化しておくのが良い気はします

2019-11-20 02:29 UTC, maru10t commented
> 
> 
> HSの問題でCIが通らない問題は、試験を一時的に無効化しておくのが良い気はします

試験の方を無効化、了解です。

2019-11-20 05:00 UTC, maru10t commented
localでのパスをメモ
```
/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Community/MSBuild/Current/Bin

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" test.sln
```

2019-11-20 07:06 UTC, maru10t commented
以下の方法で上手く行った.
* warrenbuckley/Setup-MSBuild, Setup-MSNuGet を用いて`msbuild, nuget`を持ってくる
* `nuget.exe`で明示的にboost, boost_serializationを取得
* `cmake`でvisual studio用プロジェクトファイル生成
* test.sln からは googltest の Lib/Release/*.lib を参照しているので、`msbuild googletest-distribution.sln `の際にReleaseビルドを指定

2019-11-20 07:19 UTC, maru10t commented
testケース実行までできた。最後に一通り見てリファクタリングする。

2019-11-20 07:23 UTC, LWisteria commented on .github/workflows/msbuild.yml
> +name: MSBuild
元々のccpp.ymlとかの方で私が書いたやつがあんまり良くないんですが、ファイル名やここの名前はもう少しわかりやすくしたほうが良いですね・・・

2019-11-20 08:10 UTC, maru10t commented on .github/workflows/msbuild.yml
> +name: MSBuild
* ubuntu_gcc (googletestの都合でclangではなくgcc使用のため)
* windows_msbuild
とrenameしてみました。

2019-11-20 08:11 UTC, maru10t commented
@LWisteria レビューお願いします。

2019-11-20 08:26 UTC, LWisteria requested changes
@maru10t レビューしました

2019-11-20 08:26 UTC, LWisteria commented on .github/workflows/windows_msbuild.yml
> +  build:
ビルドの中に実行(testrun)が入ってしまっていますけど、これって正しい使い方なんでしたっけ？

2019-11-20 08:26 UTC, LWisteria commented on .github/workflows/windows_msbuild.yml
> +        nuget install boost -Version 1.70.0
すみません、これが必要になった理由を改めて教えてもらえないでしょうか？

[msdoc](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-msbuild)を見ると

```
msbuild -t:restore
```

とかで動きそうに見えるんですが・・・（なぜか動かなかったようなのは見えてましたが、なんでだったんだろう？と）。

2019-11-20 08:26 UTC, LWisteria commented on .github/workflows/windows_msbuild.yml
> +      run: msbuild test.sln -p:OutDir="out/"
ビルドログを見ているとこれDebugでビルドしているように見えます。

Debugを使うことはほぼないので、Releaseでビルドしてもらえますか

2019-11-22 04:06 UTC, maru10t commented on .github/workflows/windows_msbuild.yml
> +  build:
検討しましたが、build 以下に runs-onで 実行環境指定があり、その中でビルドを行っているので、
buildからtestrunを分離すると、またtestrun以下でビルドする必要があると思いました。

`build`->`test`とリネームして、各stepがbuild, run である、と考えるのが良いのでしょうか。

2019-11-22 04:17 UTC, maru10t commented on .github/workflows/windows_msbuild.yml
> +        nuget install boost -Version 1.70.0
* 過去の動かなかったactionログのコミットでは、test.vcxprojにboost使用の設定を含ませてなかったことが分かったので、あらためて含ませてみましたが動作しませんでした。
* 本体側のOpenMPS.vcxprojに対してrestoreしてみましたが同じく動作しませんでした。
* (`src/OpenMPS.sln`と同じディレクトリ,  `src/test/test.sln`と同じディレクトリ において `msbuild -t:restore`を行った)

2019-11-22 04:17 UTC, maru10t commented on .github/workflows/windows_msbuild.yml
> +      run: msbuild test.sln -p:OutDir="out/"
修正しました

2019-11-22 05:10 UTC, maru10t commented
@LWisteria nugetの件は未解決ですが、とりあえず動く形にしました。
`msbuild -t:restore`をローカルで試行錯誤中です。

2019-11-22 05:29 UTC, aokomoriuta commented on .github/workflows/windows_msbuild.yml
> +  build:
あ、了解です。ではtestという名前で良さそうですね。

Ubuntsuの方も同じようにしてもらえますか？

2019-11-22 05:30 UTC, aokomoriuta commented on .github/workflows/windows_msbuild.yml
> +  build:
名前、単体試験なのでunittestとかのほうがいいかもしれません（他にも色んなtestがありうるので）

2019-11-22 05:32 UTC, aokomoriuta commented on .github/workflows/windows_msbuild.yml
> +        nuget install boost -Version 1.70.0
ふむ・・・なんかひっかかるんですね。

とりあえずはTODOコメント的なのを入れる＆issue立てて後回しでもいいかもしれません

2019-11-22 05:45 UTC, maru10t commented on .github/workflows/windows_msbuild.yml
> +        nuget install boost -Version 1.70.0
#37 issue立てました

2019-11-22 06:19 UTC, LWisteria requested changes
@maru10t レビューしました

2019-11-22 06:19 UTC, LWisteria commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +		/* MPS_HSをONにするとラプラシアン計算が解析解と不一致であるバグのため、コメントアウト
ここ、あとで直さないといけないので、TODOと、あとgithub issueへのリンクを貼っておいてもらえますか

2019-11-22 06:20 UTC, LWisteria commented
あ、あと、WIP外しておいてください（というか、最近はdraftという機能があるので、そっちで立ててもらうほうが良いと思います

2019-11-22 07:19 UTC, maru10t commented on src/OpenMps/test/test_ComputerExplicitForces.cpp
> +		/* MPS_HSをONにするとラプラシアン計算が解析解と不一致であるバグのため、コメントアウト
貼りました

2019-11-22 07:20 UTC, maru10t commented on .github/workflows/windows_msbuild.yml
> +  build:
unittestとリネームしました

2019-11-22 07:21 UTC, maru10t commented
@LWisteria 修正しました。(draftでのPR, 了解です)

2019-11-22 07:28 UTC, LWisteria approved these changes
修正確認しました。

2019-11-22 07:29 UTC, LWisteria commented
あ、名前変えると以前のやつが残って結果待ちになってしまうんですね。。関係ないはずなのでマージします。

2019-11-22 07:29 UTC, merged