ImplicitForces 行列求解テストを追加
openmps/openmps pull request #38
Opened 2019-11-22 08:13 UTC by maru10t

* ComputeImplicitForces() に含まれる SolvePressurePoissonEquation() 共役勾配法のテスト
    * 解析解との比較
         * 自明行列 A = k E (k定数, E単位行列) の解
         * 少し非自明な行列 A (4x4行列) の解

2019-11-22 08:13 UTC, maru10t commented
@LWisteria レビューお願いします

2019-11-22 08:23 UTC, LWisteria requested changes
@maru10t レビューしました

2019-11-22 08:23 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +}
末尾改行忘れてますね

2019-11-22 08:23 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +#include <gtest/gtest.h>
このファイルのエンコードがBOMなしになってますね・・・。

2019-11-22 08:23 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +#include "../Particle.hpp"
そういえばすっっっごい今更なんですが、このあたりのinclude要ります？Computerを入れたら不要な気がするんですが。

2019-11-22 08:23 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +	}
もうちょっと複雑で大きめな行列を解けないでしょうか。簡単な（解析解のある）ポアソン方程式とか。

2019-11-22 08:39 UTC, maru10t commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +#include "../Particle.hpp"
いらないですね。削除しました。

2019-11-22 08:40 UTC, maru10t commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +}
追加しました

2019-11-22 09:07 UTC, maru10t commented
ん？ 文字化けしている (変換前の文字と変換後の文字が共存して差分表示されている的な?)

2019-11-22 09:22 UTC, maru10t commented
### Poisson方程式 差分化メモ

こういうのを書いてる

* 1次元なら 解が f(x) だとして d^2f/dx^2 = g(x), (g(x)は何らかの関数)
* 離散化する f(x) => { f1,f2,f3,...,fN } (N分割, 各x_i での値) のように
* 微分は中心差分として d^2f/dx^2 = g(x)  => (f_i+1 + f_i-1 - 2f_i)/dx^2 = g_i  (i = 2,.., N-1 で N-2本の式)
* 境界での値を指定 f_1 = a, f_N = b ( 2本 )
* 未知数 N個{f_1,...,f_N} に対して N-2 + 2 = N 本の式ができる. これを行列形式にして SolvePoissonEquation()に解かせる

2019-11-22 10:05 UTC, maru10t commented
めも: 対称行列にするために、ディリクレ境界条件であるとして、境界値は係数行列でなく右辺で表現する

2019-11-22 10:29 UTC, maru10t commented
(次回todo memo: 対称行列として離散化まで書いたので、次は解析解との比較を追加する)

2019-11-25 08:33 UTC, maru10t commented
![texclip20191125173213](https://user-images.githubusercontent.com/5325357/69524579-b2b02780-0fa9-11ea-97c8-394f23ac542e.png)

2019-11-25 08:50 UTC, maru10t commented
f(0) = 0, f(1) = 1 で計算. たぶん添え字ミスでずれてるので修正中
Left: numerical, Right: analytical, f(x_i) ( i = 1,..,N, N = 30)
```
0: 0.0268873, 0.0322581
1: 0.0538082, 0.0645161
2: 0.0807962, 0.0967742
3: 0.107885, 0.129032
4: 0.135108, 0.16129
5: 0.162499, 0.193548
6: 0.190091, 0.225806
7: 0.217918, 0.258065
8: 0.246014, 0.290323
9: 0.274412, 0.322581
10: 0.303145, 0.354839
11: 0.332248, 0.387097
12: 0.361754, 0.419355
13: 0.391695, 0.451613
14: 0.422107, 0.483871
15: 0.453023, 0.516129
16: 0.484475, 0.548387
17: 0.516498, 0.580645
18: 0.549126, 0.612903
19: 0.582391, 0.645161
20: 0.616327, 0.677419
21: 0.650968, 0.709677
22: 0.686348, 0.741935
23: 0.7225, 0.774194
24: 0.759458, 0.806452
25: 0.797254, 0.83871
26: 0.835924, 0.870968
27: 0.875499, 0.903226
28: 0.916015, 0.935484
29: 0.957504, 0.967742
```

2019-11-25 10:03 UTC, maru10t commented
一致した。 (解析解表示の方がダメだったやつや...)
あとは解析解との相対誤差判定コードを追加する
```
dx: 0.0322581
-1: 0
0: 0.0268873, 0.0268873
1: 0.0538082, 0.0538082
2: 0.0807962, 0.0807962
3: 0.107885, 0.107885
4: 0.135108, 0.135108
5: 0.162499, 0.162499
6: 0.190091, 0.190091
7: 0.217918, 0.217918
8: 0.246014, 0.246014
9: 0.274412, 0.274412
10: 0.303145, 0.303145
11: 0.332248, 0.332248
12: 0.361754, 0.361754
13: 0.391695, 0.391695
14: 0.422107, 0.422107
15: 0.453023, 0.453023
16: 0.484475, 0.484475
17: 0.516498, 0.516498
18: 0.549126, 0.549126
19: 0.582391, 0.582391
20: 0.616327, 0.616327
21: 0.650968, 0.650968
22: 0.686348, 0.686348
23: 0.7225, 0.7225
24: 0.759458, 0.759458
25: 0.797254, 0.797254
26: 0.835924, 0.835924
27: 0.875499, 0.875499
28: 0.916015, 0.916015
29: 0.957504, 0.957504
30: 1
```

2019-11-25 10:20 UTC, maru10t commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +	}
簡単すぎるかもですが、1次元ポアソン方程式のテストを追加しました。

2019-11-25 10:22 UTC, maru10t commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +#include <gtest/gtest.h>
再度作成して変換してみました

2019-11-25 10:26 UTC, maru10t commented
@LWisteria レビューお願いします。

2019-11-29 06:02 UTC, LWisteria requested changes
@maru10t レビューしました

2019-11-29 06:02 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +					ppe.A(i, j) = 0.0;
疎行列の全面に0を個別代入するのは無駄が多すぎます。普通にclear()があるのでそれが使えます

2019-11-29 06:02 UTC, LWisteria commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +				ppe.b(j) = 0.0;
ベクトルも同様です

2019-11-29 06:12 UTC, maru10t commented on src/OpenMps/test/test_ComputerConjugateGradient.cpp
> +					ppe.A(i, j) = 0.0;
はい、対応しました。

2019-11-29 06:12 UTC, maru10t commented
@LWisteria 修正しました。

2019-11-29 06:24 UTC, LWisteria approved these changes
LGTM

2019-11-29 06:25 UTC, merged