WIP: 圧力勾配力による位置・速度更新のテスト
openmps/openmps pull request #40
Opened 2019-11-29 06:39 UTC by maru10t

2019-11-29 06:42 UTC, maru10t commented
P(x,z) = 10*z として粒子を配置 (5x5格子, 中心粒子における値を評価)
```
dpx: 2.22045e-16, dpz: 11.2132
```
少しずれる。調整中。

2019-11-29 07:03 UTC, maru10t commented
5x5, r_e = 1.5l0, l0 = 1.0, 近傍粒子の座標を出力. 
想定通り, 中心粒子20 の周囲8粒子が, gradient計算時の AccumulateNeighbor で加算されている
```
particle: 12
thisX (2,2)
x (1,1)
x (2,1)
x (1,2)
x (1,3)
x (2,3)
x (3,1)
x (3,2)
x (3,3)
```

2019-11-29 07:05 UTC, maru10t commented
PRESSURE_GRADIENT_MIDPOINT が ON だから圧力は2粒子間の中点で評価される。ということを考慮すると...?

2019-11-29 07:09 UTC, maru10t commented
memo: PRESSURE_GRADIENT_MIDPOINT の OFF は 現在コンパイル通らない

2019-11-29 07:21 UTC, maru10t commented
```c++
//const Vector result = ((p + thisP) / r2 * Particle::W(std::sqrt(r2), r_e)) * dx;
const Vector result = ((p - thisP) / r2 * Particle::W(std::sqrt(r2), r_e)) * dx;
```

* こうして中点評価をやめても(?)　値は変わらず(dpz=11.2132)
* →prefactor(dt,n0,など) 評価を疑う

2019-12-13 01:32 UTC, maru10t commented
係数設定を勘違いしていた。(prefactにn0は当然入るはずはない)
一致した。(理論値: dpx=0, dpz=10)
```
dpx: 1.98021e-16
dpz: 10
```

2019-12-13 02:03 UTC, LWisteria requested changes
@maru10t レビューしました

2019-12-13 02:03 UTC, LWisteria commented on src/OpenMps/test/test_ComputerModifyByPressureGradient.cpp
> +		const double dpx = p[12].U()[OpenMps::AXIS_X] / prefact;
このへんの`12`は、`num_x/2`とかですかね？マジックナンバー良くないので修正してもらえますか（実は他のファイルもだったりします？

2019-12-13 02:03 UTC, LWisteria commented on src/OpenMps/test/test_ComputerModifyByPressureGradient.cpp
> +				particle.P() = j*gradp;
これだと1次元の平坦な勾配しか確認できていない（＆z方向を確認していない）ことになると思うので、もう少し複雑な形状での試験も追加してもらえますか。

2019-12-13 02:04 UTC, maru10t commented on src/OpenMps/test/test_ComputerModifyByPressureGradient.cpp
> +		const double dpx = p[12].U()[OpenMps::AXIS_X] / prefact;
わかりました。この辺統一されてないので、まとめて修正します

2019-12-13 02:06 UTC, maru10t commented on src/OpenMps/test/test_ComputerModifyByPressureGradient.cpp
> +				particle.P() = j*gradp;
「複雑な形状」というのは、粒子配置が非等間隔格子を指すのではなくて、
速度分布が複雑ということですよね？
でしたら、2次, 三角関数 を追加してみます。

2019-12-13 02:49 UTC, maru10t commented
TODO: tab, 文字コードに注意

2019-12-20 07:35 UTC, maru10t commented
* commit f171aa3653a1b8ea 後にCI通らなくなったので修正中
* 手元(Windows + Mac)ではビルドとテストが通る

* CI-Windows: ビルドエラー,  ViennaCLの問題? 
       * `D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(99,23): error C2039: 'inner_prod_cpu': is not a member of 'viennacl::linalg'[D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]`

* CI-Ubuntu: 速度変化の挙動に問題がありそう (しかし, CIは通る)
* 手元とCIでの結果が異なるため、未初期化的な問題 or範囲外参照しているなど?

出力方法
```
std::cout << "du: " << du << std::endl;
std::cout << "dpx*x*prefact: " << dpx*x*prefact << std::endl;
```

Local (Windows, Mac)での結果
```
[----------] 1 test from PressureGradientTest
[ RUN      ] PressureGradientTest.CompareGradientProfile
du: -0.000369665
dpx*x*prefact: -0.000369665
du: -0.000492887
dpx*x*prefact: -0.000492887
du: -0.000616109
dpx*x*prefact: -0.000616108
du: -0.000739331
dpx*x*prefact: -0.00073933
```

CI Ubuntuでの結果. 
```
[----------] 1 test from PressureGradientTest
[ RUN      ] PressureGradientTest.CompareGradientProfile
du: 0
dpx*x*prefact: -0.000369665
du: 0
dpx*x*prefact: -0.000492887
du: 0
dpx*x*prefact: -0.000616109
du: 0
dpx*x*prefact: -0.000739331
du: 0
```

2019-12-20 08:41 UTC, maru10t commented
* 前回のCI通過時点 c62033e6b2a まで復元してCIに投げたが、Windows-CIが失敗した。
* エラー内容は同様のViennaCL
``` D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(99,23): error C2039: 'inner_prod_cpu': is not a member of 'viennacl::linalg'[D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]```

2019-12-20 08:53 UTC, maru10t commented
* Ubuntu-CI環境では粒子速度が正しく取ってこれておらず0として評価される。
          * しかし相対誤差で比べていなかったので、テストをPASSしている。
* Windows-CIが通らない問題は試行錯誤中。

2019-12-20 09:02 UTC, maru10t commented
* (想定通り?)  Ubuntu-CI, Windows-CI ともにPASSしなくなった。
* 速度取得失敗の解決から着手

2019-12-20 09:16 UTC, maru10t commented
初期条件設定は動作していて、ModifyByPressureGradient() による 圧力勾配からの速度更新が動いてない

```
---------local---------
[0] x=-0.000000,z=-0.000000,u=-0.000003,v=-0.000047,p=0.000000
[1] x=1.000000,z=-0.000001,u=0.000000,v=-0.000050,p=0.000000
[2] x=2.000000,z=-0.000001,u=0.000000,v=-0.000050,p=0.000000
[3] x=3.000000,z=-0.000001,u=0.000000,v=-0.000050,p=0.000000
[4] x=4.000000,z=-0.000000,u=0.000003,v=-0.000047,p=0.000000
[5] x=-0.000000,z=0.999999,u=-0.000040,v=-0.000095,p=10.000000
[6] x=1.000000,z=0.999999,u=0.000000,v=-0.000100,p=10.000000
[7] x=2.000000,z=0.999999,u=0.000000,v=-0.000100,p=10.000000
[8] x=3.000000,z=0.999999,u=0.000000,v=-0.000100,p=10.000000
[9] x=4.000000,z=0.999999,u=0.000040,v=-0.000095,p=10.000000
[10] x=-0.000001,z=1.999999,u=-0.000080,v=-0.000095,p=20.000000
[11] x=1.000000,z=1.999999,u=-0.000000,v=-0.000100,p=20.000000
[12] x=2.000000,z=1.999999,u=-0.000000,v=-0.000100,p=20.000000
[13] x=3.000000,z=1.999999,u=-0.000000,v=-0.000100,p=20.000000
[14] x=4.000001,z=1.999999,u=0.000080,v=-0.000095,p=20.000000
[15] x=-0.000001,z=2.999999,u=-0.000121,v=-0.000095,p=30.000000
[16] x=1.000000,z=2.999999,u=-0.000000,v=-0.000100,p=30.000000
[17] x=2.000000,z=2.999999,u=-0.000000,v=-0.000100,p=30.000000
[18] x=3.000000,z=2.999999,u=-0.000000,v=-0.000100,p=30.000000
[19] x=4.000001,z=2.999999,u=0.000121,v=-0.000095,p=30.000000
[20] x=0.000001,z=3.999999,u=0.000058,v=-0.000103,p=40.000000
[21] x=1.000000,z=4.000001,u=0.000000,v=0.000111,p=40.000000
[22] x=2.000000,z=4.000001,u=0.000000,v=0.000111,p=40.000000
[23] x=3.000000,z=4.000001,u=0.000000,v=0.000111,p=40.000000
[24] x=3.999999,z=3.999999,u=-0.000058,v=-0.000103,p=40.000000

----------- CI -------
[0] x=0.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[1] x=1.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[2] x=2.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[3] x=3.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[4] x=4.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[5] x=0.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[6] x=1.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[7] x=2.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[8] x=3.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[9] x=4.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[10] x=0.000000,z=2.000000,u=0.000000,v=0.000000,p=20.000000
[11] x=1.000000,z=2.000000,u=0.000000,v=0.000000,p=20.000000
[12] x=2.000000,z=2.000000,u=0.000000,v=0.000000,p=20.000000
[13] x=3.000000,z=2.000000,u=0.000000,v=0.000000,p=20.000000
[14] x=4.000000,z=2.000000,u=0.000000,v=0.000000,p=20.000000
[15] x=0.000000,z=3.000000,u=0.000000,v=0.000000,p=30.000000
[16] x=1.000000,z=3.000000,u=0.000000,v=0.000000,p=30.000000
[17] x=2.000000,z=3.000000,u=0.000000,v=0.000000,p=30.000000
[18] x=3.000000,z=3.000000,u=0.000000,v=0.000000,p=30.000000
[19] x=4.000000,z=3.000000,u=0.000000,v=0.000000,p=30.000000
[20] x=0.000000,z=4.000000,u=0.000000,v=0.000000,p=40.000000
[21] x=1.000000,z=4.000000,u=0.000000,v=0.000000,p=40.000000
[22] x=2.000000,z=4.000000,u=0.000000,v=0.000000,p=40.000000
[23] x=3.000000,z=4.000000,u=0.000000,v=0.000000,p=40.000000
[24] x=4.000000,z=4.000000,u=0.000000,v=0.000000,p=40.000000
```

2019-12-20 09:21 UTC, maru10t commented
defines.hpp は ローカル/CIで同一

2019-12-20 09:44 UTC, maru10t commented
ModifyByPressure は Callされていることは確か。
その中の速度勾配の評価が機能してない。
```
on CI

p[1].u: += 0
p[1].v: += 0
p[2].u: += 0
p[2].v: += 0
p[3].u: += 0
p[3].v: += 0
```

2019-12-20 09:59 UTC, maru10t commented
PRESSURE_GRADIENT_MIDPOINT 以下の AccumuNeighbor 直後に 計算された値を出力. ゼロとなっているっぽい。次はそもそもModifyByPressureGradientから正しく粒子物理量が見えているのか？をチェック
```
on CI

ModifyByPressureGradient() Called
du[0]: += du[13]: += 0
dv[13]: += 0
du[14]: += -0
dv[14]: += 0
du[15]: += 0
dv[15]: += 0
du[16]: += 0
dv[16]: += 0
du[17]: += 0
dv[17]: += 0
du[18]: += 0
```

2019-12-20 10:08 UTC, maru10t commented
ModifyBy...Call直後には正しく見えているようだ
```
on CI
---------

ModifyByPressureGradient() Called
[0] x=0.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[1] x=1.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[2] x=2.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[3] x=3.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[4] x=4.000000,z=0.000000,u=0.000000,v=0.000000,p=0.000000
[5] x=0.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[6] x=1.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[7] x=2.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[8] x=3.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
[9] x=4.000000,z=1.000000,u=0.000000,v=0.000000,p=10.000000
```

2019-12-20 10:18 UTC, maru10t commented
とりあえず深く考える前に、CI側がバージョンアップするなどでおかしくなった説を検証。
まずはUbuntuバージョン下げてみる。

2019-12-20 10:20 UTC, maru10t commented
16.04 を指定してみた。コンパイルエラーでこけた。

2019-12-20 10:24 UTC, maru10t commented
コンパイルエラー考えるのめんどくさいので...バージョン下げる代わりに手元の Ubuntu-18.04 での動作を試してみる。現在のgithub worklflowのubuntu-latestで指定されるのは, Ubuntu-18.04らしい。

2019-12-25 05:24 UTC, maru10t commented
Ubuntu-CI上で 圧力勾配からの速度変化が0となる問題について、

AccumulateNeighbor中とその前後にprintf仕込むことで、
返り値resultの段階では非ゼロの値を持っているが、Accumulate後のdはゼロになることがわかった。(デバッグ出力側の問題でないことは, cout/printf両方で0であることの確認, ASSEERT_NEARの値評価でそもそも0であることから確認)

該当箇所
```cpp
#ifdef PRESSURE_GRADIENT_MIDPOINT
					// 速度修正量を計算
					// 標準MPS法：-Δt/ρ D/n_0 (p_j + p_i)/r^2 w * dx
					const auto d = (-dt / rho * DIM / n0) * AccumulateNeighbor<Detail::Field::Name::P, Detail::Field::Name::X, Detail::Field::Name::Type>(i, VectorZero,
						[thisP = particle.P(), thisX = particle.X(), r_e](const auto p, const auto& x, const auto type)
					{
						// ダミー粒子以外
						if(type != Particle::Type::Dummy)
						{
							namespace ublas = boost::numeric::ublas;

							const auto dx = x - thisX;
							const auto r2 = ublas::inner_prod(dx, dx);
							const Vector result = ((p + thisP) / r2 * Particle::W(std::sqrt(r2), r_e)) * dx;
							printf("[gradp midp] thisP: %f, p: %f, result: %f,%f\n", thisP, p, result[OpenMps::AXIS_X], result[OpenMps::AXIS_Z]);
							return result;
						}
```

2019-12-25 05:31 UTC, maru10t commented
AccumulateNeighborの返り値である速度変化量の型解釈がg++バージョンで異なる、的なやつかな

2019-12-25 05:37 UTC, maru10t commented
### Mac

g++ version
```
~/Workspace/openmps/src/OpenMps/test (14_pressgrad *$=) $ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

outputs
```
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.000000,5.000000
[gradp midp] thisP: 0.000000, p: 0.000000, result: 0.000000,0.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.303301,0.303301
[gradp midp] thisP: 0.000000, p: 0.000000, result: -0.000000,-0.000000
du: -0.000003, dv: -0.000047
[gradp midp] thisP: 0.000000, p: 0.000000, result: -0.000000,0.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: -0.303301,0.303301
[gradp midp] thisP: 0.000000, p: 0.000000, result: 0.000000,0.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.000000,5.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.303301,0.303301
[gradp midp] thisP: 0.000000, p: 0.000000, result: 0.000000,-0.000000
du: -0.000000, dv: -0.000050
```

### Ubuntu-CI, ubuntu-latest

```
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.000000,5.000000
[gradp midp] thisP: 0.000000, p: 0.000000, result: 0.000000,0.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.303301,0.303301
[gradp midp] thisP: 0.000000, p: 0.000000, result: -0.000000,-0.000000
du: 0.000000, dv: 0.000000
[gradp midp] thisP: 0.000000, p: 0.000000, result: -0.000000,0.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: -0.303301,0.303301
[gradp midp] thisP: 0.000000, p: 0.000000, result: 0.000000,0.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.000000,5.000000
[gradp midp] thisP: 0.000000, p: 10.000000, result: 0.303301,0.303301
[gradp midp] thisP: 0.000000, p: 0.000000, result: 0.000000,-0.000000
du: 0.000000, dv: 0.000000
```

2019-12-25 06:02 UTC, maru10t commented
typeidで型の解釈が同じであることを確認

Mac
```
id[14] du: 0.000080, dv: -0.000095
N5boost7numeric5ublas21vector_binary_scalar1IKdNS1_8c_vectorIdLm2EEENS1_17scalar_multipliesIddEEEE
d
[gradp midp] thisP: 30.000000, p: 20.000000, result: 0.000000,-25.000000
N5boost7numeric5ublas8c_vectorIdLm2EEE
d
```

Ubuntu-CI, ubuntu-latest
```
id[14] du: -0.000000, dv: 0.000000
N5boost7numeric5ublas21vector_binary_scalar1IKdNS1_8c_vectorIdLm2EEENS1_17scalar_multipliesIddEEEE
d
[gradp midp] thisP: 30.000000, p: 20.000000, result: 0.000000,-25.000000
N5boost7numeric5ublas8c_vectorIdLm2EEE
d
```

2019-12-25 06:13 UTC, LWisteria commented
@maru10t 自動型推論(auto)と式テンプレートの相性が悪く、そこが悪さをしている可能性がありますね・・・。その解決には明示的に型キャストをする必要があります。

2019-12-25 06:17 UTC, maru10t commented
@LWisteria なるほど。つぎは手当たり次第に明示的型指定(auto を double, Vector)を試してみますね。

2019-12-25 06:19 UTC, LWisteria commented
相性が悪い理由とかはこのあたりが詳しいかと思います https://pepshiso.hatenadiary.org/entry/20101228/1293548263

2019-12-25 07:55 UTC, maru10t commented
* Ubuntu-CI の latest は, Ubuntu 18.04 で g++ 7.4.0 
* 手元のUbuntuは16.04だったので, gcc-7 を指定してインストール

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-7 -y
```

2019-12-25 07:57 UTC, maru10t commented
```
:~$ g++-7 --version
g++-7 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

2019-12-25 08:07 UTC, maru10t commented
Ubuntu16.04 + g++-7.4.0 で 速度変化が0となる症状を確認した。

2019-12-25 08:23 UTC, maru10t commented
```
const auto d = (-dt / rho * DIM / n0) * AccumulateNeighbor<Detail::Field::Name::P, Detail
```
を
```
const Vector d = (-dt / rho * DIM / n0) * AccumulateNeighbor<Detail::Field::Name::P, Detail
```
にしたら、速度0症状が解決した。

2019-12-25 08:24 UTC, LWisteria commented
なるほど・・・確かにAccumulateNeighbor()が返ってくる時点ではVectorだけどそれにスカラー乗算が入って式テンプレートになっちゃうのか・・・なるほど。

2019-12-25 09:01 UTC, maru10t commented
次はmsbuild通らなくなった問題を解決する

2020-01-10 00:27 UTC, maru10t commented
手元のWindows環境において、同様のビルドオプションでビルド成功を確認した。
```
>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" test.sln -p:Configuration=Release -p:OutDir="out/"
.NET Framework 向け Microsoft (R) Build Engine バージョン 16.1.76+g14b0a930a7
Copyright (C) Microsoft Corporation.All rights reserved.

(中略)

ビルドに成功しました。
    0 個の警告
    0 エラー
```

2020-01-10 00:33 UTC, maru10t commented
CIで吐かれているエラー. msbuildのバージョンが変わるなどして、ViennaCLヘッダの#ifdefがうまく機能してない...的な印象。ヘッダの中身見る前にWindowsバージョン下げて試してみる。
```
2
D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(99,23): error C2039: 'inner_prod_cpu': is not a member of 'viennacl::linalg' [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
23
D:\a\openmps\openmps\src\viennacl\viennacl\linalg\scalar_operations.hpp(47): message : see declaration of 'viennacl::linalg' [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
24
D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(106): message : see reference to class template instantiation 'viennacl::scalar_expression<LHS,RHS,viennacl::op_inner_prod>' being compiled [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
25
D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(132,23): error C2039: 'norm_1_cpu': is not a member of 'viennacl::linalg' [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
26
D:\a\openmps\openmps\src\viennacl\viennacl\linalg\scalar_operations.hpp(47): message : see declaration of 'viennacl::linalg' [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
27
D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(139): message : see reference to class template instantiation 'viennacl::scalar_expression<LHS,RHS,viennacl::op_norm_1>' being compiled [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
28
D:\a\openmps\openmps\src\viennacl\viennacl\scalar.hpp(164,23): error C2039: 'norm_2_cpu': is not a member of 'viennacl::linalg' [D:\a\openmps\openmps\src\OpenMps\test\test.vcxproj]
```

2020-01-10 00:40 UTC, maru10t commented
https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2016
* windows-latest で windows server 2019 が指定される
* wndows server 2016 は削除され、指定できない

2020-01-10 00:52 UTC, maru10t commented
* scalar.hpp で `inner_prod_cpu`, (略) が未定義なエラー
* エラーとして挙げられている未定義関数 は linalg/vector_operation.hpp で宣言されている

2020-01-10 01:20 UTC, maru10t commented
* Computer.hpp で linalg/vector_operation.hpp を 明示的に最初にインクルードしてみたが、同様のエラー
* → CI上でのMSBuildバージョンに対して #ifdef が 機能してなさそう?

2020-01-10 01:31 UTC, maru10t commented
* ViennaCLでなく、boostを使用するようdefines.hpp変更してみた。
* → msbuild, ubuntu ともにビルド成功。しかし、ubuntu側のみC++ Exceptionでテストが通らない。

```
[----------] 3 tests from ConjugateGradientTest
[ RUN      ] ConjugateGradientTest.SolveIdentityMatrix
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] ConjugateGradientTest.SolveIdentityMatrix (1 ms)
[ RUN      ] ConjugateGradientTest.Solve4x4Matrix
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] ConjugateGradientTest.Solve4x4Matrix (0 ms)
[ RUN      ] ConjugateGradientTest.Solve1dODE
[       OK ] ConjugateGradientTest.Solve1dODE (0 ms)
[----------] 3 tests from ConjugateGradientTest (1 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 6 test suites ran. (20 ms total)
[  PASSED  ] 16 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] ConjugateGradientTest.SolveIdentityMatrix
[  FAILED  ] ConjugateGradientTest.Solve4x4Matrix

 2 FAILED TESTS
##[error]Process completed with exit code 1.
```

2020-01-10 01:43 UTC, maru10t commented
memo: 
msbuild の path
* ```"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"```

2020-01-10 02:51 UTC, maru10t commented
手元の Ubuntu 16.04 + g++-7 では再現せず > boost用いると ConjugateGradientが落ちる

2020-01-10 03:16 UTC, maru10t commented
* 手元(mac gcc,Windows msbuild,Ubuntu16.04 gcc)では再現しなかったが、CI上では、Windows-CI, Ubuntu-CI ともに起こる、かつ実行のたびに動作が変わっている(これはWindows-CIで確認した)ため、
ConjugateGradientでの計算で範囲外参照などを起こしている印象である。

2020-01-10 03:22 UTC, maru10t commented
@LWisteria 
ViennaCL, Boost ともにCIでの問題にぶつかっています(手元では動く)。
どちらに時間を割くべきでしょうか？ もしくは 両方解決させますか？

以下のように、だいたいの原因はわかっています。

* ViennaCL:
      * Windows-CIがコンパイルエラー。今回追加したtest部分でなくて、msbuildとviennaCLのバージョンの相性が問題である。
* Boost:
      * コンパイルは通る。Ubuntu-CI,Windows-CIともに ConjugateGradient 計算が実行時例外で落ちる。範囲外参照などで例外出している印象。

2020-01-10 06:05 UTC, LWisteria commented
うーん。CIいったん切りましょう。原因がPRと全然関係ないとこにあるので、別issueが良いと思います

2020-01-10 06:08 UTC, maru10t commented
@LWisteria 了解です。本PRがマージされるまで切って作業します。
本PRにはCIデバッグ用のコミットが大量に含まれていますが、これはそのままで良いでしょうか？

2020-01-10 06:13 UTC, maru10t commented
@LWisteria 無効化はworflowのymlを除外(リネーム?)すれば良いんですかね？

2020-01-10 06:23 UTC, LWisteria commented
うーん。デバッグコミットはどうしましょうね。。
普段ならそのままでもと思うんですが、流石に多すぎですかね。

CI無効化する（拡張子とか変える）PRと、このPRの本体と2つに分離しましょうか

2020-01-10 06:27 UTC, maru10t commented
(個人的にめっちゃコミットログ汚してしまったぁという感情が。)
@LWisteria はい、PR分けること了解です!

2020-01-10 08:22 UTC, LWisteria commented
ではこっちは閉じておきます

2020-01-10 08:22 UTC, closed without merging

2020-01-10 08:24 UTC, LWisteria commented
@maru10t ついでに伝えておくと、CIはPRになってなくても実行されるので、デバッグするならデバッグ用ブランチを作って思う存分あれこれ気兼ねなくしちゃってください。