圧力勾配力の計算テスト
openmps/openmps pull request #48
Opened 2020-01-10 07:21 UTC by maru10t

圧力勾配力による位置・速度の更新のテスト

2020-01-10 07:22 UTC, maru10t commented
TODO: 空間の中央でのみ値比較しているため、
空間的に広がりがある圧力分布の場合の値比較を追加する。

2020-01-10 08:10 UTC, maru10t commented
高次多項式の圧力分布のテスト、微分デバッグ

```
particle.P() = c1 * x + c2 * z * z * z;
```

c2の値によらず 0.01333 だけずれる。(c2 = 0.1, 0.01オーダで確認) 
```
[ RUN      ] PressureGradientTest.GradValue
C:\Users\takafumi.maruishi\Workspace\openmps\src\OpenMps\test\test_ComputerPresureGradient.cpp(158): error: The difference between abs( (dv - gradpz * prefact) / (gradpz * prefact) ) and 0.0 is 0.013333333333333199, which exceeds testAccuracy, where
abs( (dv - gradpz * prefact) / (gradpz * prefact) ) evaluates to 0.013333333333333199,
0.0 evaluates to 0, and
testAccuracy evaluates to 0.001.
[  FAILED  ] PressureGradientTest.GradValue (14 ms)
```

2020-01-24 03:39 UTC, maru10t commented
* 3次でずれる現象
* 15x15配置
* 壁から離れた場所(i,j)=(7,7)での圧力分布比較
* p(x,z) = a x^3 + b z^3という圧力分布
*  空間変化スケールを粒子相互作用半径のn倍とした。具体的には a = 1/(n * r_e)^3, b = 1/(n * r_e)^3 

変化スケール 10 r_e
dpx_num/dpx_analy: 0.0146173/0.0145185, relErr=0.00680272
dpz_num/dpz_analy: -0.219259/-0.217778, relErr=0.00680271

変化スケール 100 r_e
dpx_num/dpx_analy: 1.46173e-05/1.45185e-05, relErr=0.00680272
dpz_num/dpz_analy: -0.00219259/-0.00217778, relErr=0.00680272

→解像度で収束してないので、テスト時にでまぎれこませた添字ミスかも。確認中

2020-01-24 04:24 UTC, maru10t commented
* 添字と位置の対応がミスっている説: x (すべて出力して確認)
* 解析解側の評価のチェック: x (解析解の評価に使われる位置がずれている説)
* 空間範囲を超えている説: x (maxX などを引き上げても変わらず)
* 圧力が中点評価なので, 解析解とはそもそもずれる説:  x? (圧力勾配をかなり低く設定したが誤差は変化しなかったため)
* 壁の影響説: (num_x, num_zを変化させたが変化せず)

空間の絶対位置に依存した誤差である

```
[i,j] = 3, 4: 
dpx_num/dpx_analy: 0.00276543/0.00266667, relErr=0.037037
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 4, 4: 
dpx_num/dpx_analy: 0.00483951/0.00474074, relErr=0.0208333
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 5, 4: 
dpx_num/dpx_analy: 0.00750617/0.00740741, relErr=0.0133333
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 6, 4: 
dpx_num/dpx_analy: 0.0107654/0.0106667, relErr=0.00925926
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 7, 4: 
dpx_num/dpx_analy: 0.0146173/0.0145185, relErr=0.00680272
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 8, 4: 
dpx_num/dpx_analy: 0.0190617/0.018963, relErr=0.00520833
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 9, 4: 
dpx_num/dpx_analy: 0.0240988/0.024, relErr=0.00411523
dpz_num/dpz_analy: -0.00483951/-0.00474074, relErr=0.0208333
[i,j] = 10, 4: 
dpx_num/dpx_analy: 0.0297284/0.0296296, relErr=0.00333333
```

次数変化させてみた, dl は空間変化スケール
```
2次 dl = 10 r_e, [i,j] = 7,7
dpx_num/dpx_analy: 0.0311111/0.0311111, relErr=1.11518e-16
dpz_num/dpz_analy: -0.0311111/-0.0311111, relErr=-0

2次, dl = 1 r_e  [i,j] = 7, 7: 
dpx_num/dpx_analy: 3.11111/3.11111, relErr=0
dpz_num/dpz_analy: -3.11111/-3.11111, relErr=-0
```
4次, dl = 10 r_e
dpx_num/dpx_analy: 0.00691358/0.00677531, relErr=0.0204082
dpz_num/dpz_analy: -0.00691358/-0.00677531, relErr=0.0204082

dl = 1 r_e
dpx_num/dpx_analy: 69.1358/67.7531, relErr=0.0204082
dpz_num/dpz_analy: -69.1358/-67.7531, relErr=0.0204082
```

2020-01-24 04:38 UTC, maru10t commented
@LWisteria 
この誤差問題、もう少し時間をかけて良さそうでしょうか？  
この後は粒子配置、勾配モデルの問題点だったりするでしょうか？
どれも相対誤差で5%以下のずれで実用的には許容できそうな気もします。

2020-01-24 04:40 UTC, maru10t commented
TODO: 三角関数の波長変化させて似たデータ取る?

2020-01-24 05:54 UTC, LWisteria commented
@maru10t その問題の高次多項式のコードってどこにありますか？確認できないのでなんとも言えない・・・。

2020-01-24 05:54 UTC, maru10t commented
@LWisteria コミットします。おまちを

2020-01-24 06:01 UTC, maru10t commented
todo: abs を relErr へ

2020-01-24 06:04 UTC, LWisteria commented
んー。コード中は特に不審な点はないですね。
となると、実装/理論どちらかに不備があるんだと思います。

@maru10t とりあえず「不合格」であることは現状だと仕方ないとして、改善・修正は別チケットでやりましょうか。

2020-01-24 06:07 UTC, maru10t commented
@LWisteria なるほど。わかりました > 改善・修正は別チケットで
では
* 5%程度の誤差は許すように設定しておく
* 同様にして三角関数のテストも作成
とします

2020-01-24 07:00 UTC, maru10t commented
あれ？バッジ（CIの)が表示されている？

2020-01-24 07:04 UTC, maru10t commented
@LWisteria レビューお願いします。Github Actionがまた有効になっているようなので、そちらの設定確認もお願いします。

2020-01-24 07:05 UTC, LWisteria approved these changes
レビューしました

2020-01-24 07:05 UTC, LWisteria commented on src/OpenMps/test/test_ComputerPressureGradient.cpp
> +        // 2次、3次の多項式からなる圧力分布のテスト
indent

2020-01-24 07:05 UTC, LWisteria commented on src/OpenMps/test/test_ComputerPressureGradient.cpp
> +        // 三角関数からなる圧力分布のテスト
こっちも

2020-01-24 07:06 UTC, LWisteria requested changes
（間違えてapproveしてしまった

2020-01-24 07:13 UTC, maru10t commented on src/OpenMps/test/test_ComputerPressureGradient.cpp
> +        // 2次、3次の多項式からなる圧力分布のテスト
入れました

2020-01-24 07:13 UTC, maru10t commented on src/OpenMps/test/test_ComputerPressureGradient.cpp
> +        // 三角関数からなる圧力分布のテスト
追加しました

2020-01-24 07:13 UTC, maru10t commented
@LWisteria 修正しました

2020-01-24 07:21 UTC, LWisteria requested changes
レビューしました。修正方法間違ってます。

2020-01-24 07:21 UTC, LWisteria commented on src/OpenMps/test/test_ComputerPresureGradient.cpp
> +#include <gtest/gtest.h>
またgit mvせずに手動で追加してませんか

2020-01-24 07:22 UTC, LWisteria commented
@maru10t あと、Github Actionは生きているままで正しくて、マージをブロックすることがなくなっているだけです。ubuntu側は動いているはずなので（ですよね？）、そっちは結果間違ってないか見てください。

2020-01-24 07:26 UTC, maru10t commented on src/OpenMps/test/test_ComputerPresureGradient.cpp
> +#include <gtest/gtest.h>
修正しました

> history
```
  790  git add test_ComputerPresureGradient.cpp 
  791  git mv test_ComputerPresureGradient.cpp test_ComputerPressureGradient.cpp
  803  git commit -m "Fix type"
```
としていたようです。

2020-01-24 07:27 UTC, LWisteria commented on src/OpenMps/test/test_ComputerPresureGradient.cpp
> +#include <gtest/gtest.h>
最初のgit addが完全に余計ですね・・・

2020-01-24 07:27 UTC, maru10t reviewed
@LWisteria なるほど了解です。現在のコミットはUbuntu側ちゃんと生きているようです。
手元(このページ)では、"Merging is blocked"と表示されていたので、勘違いしてました。

2020-01-24 07:28 UTC, LWisteria commented
"Merging is blocked"は、私のレビューが終わってないからです

2020-01-24 07:29 UTC, maru10t commented on src/OpenMps/test/test_ComputerPresureGradient.cpp
> +#include <gtest/gtest.h>
でした..

2020-01-24 07:29 UTC, LWisteria requested changes
間違ったファイルを消したのはいいんですが、レビュー指摘直っていませんよ・・・（古いファイルが残っているので）

2020-01-24 07:31 UTC, maru10t commented
おっと？ すみません確認します

2020-01-24 07:37 UTC, maru10t commented
@LWisteria 
確認不足失礼しました。修正しました！

2020-01-24 07:41 UTC, LWisteria approved these changes
LGTM

2020-01-24 07:43 UTC, merged