粒子数密度増加速度のテスト追加
openmps/openmps pull request #52
Opened 2020-01-30 10:02 UTC by maru10t

#44 NeighborDensityVariationSpeed() のテスト追加。解析値との空間に渡る比較を行う。

2020-01-30 10:18 UTC, maru10t commented
* 発散が非ゼロである簡単な流れ場を与えてテストする。粒子数密度増加速度は速度場発散に比例する。
* 多項式で`(u,v) = (x, 0)`や`(u,v) = (0,y)`の形のものを与えて計算してみる

2020-01-30 10:35 UTC, maru10t commented
* 標準MPSの計算中身↓
```
			const auto n0 = environment.N0();
			const auto dt = environment.Dt();
			const auto thisN = particles[i].N();

			// 標準MPS法：b_i = (n_i - n0)/Δt
			const auto result = (thisN - n0) / dt;
```
* 基準数密度n0はenvironmentのコンストラクタで計算。影響半径r_e, 長さl0 から。
* 初期条件の作り方次第でthisN != n0 である

2020-01-31 02:27 UTC, maru10t commented
* 連続的に考えると 1/n0 * dndt = div(u) であるはず

* いまデフォルトで用いられてるのは高精度のこっち
```
			// HS法（高精度生成項）：-r_eΣ r・u / |r|^3
			const auto result  =
				-r_e * AccumulateNeighbor<Detail::Field::Name::X, Detail::Field::Name::U>(i, 0.0,
				[&thisX = particles[i].X(), &thisU = particles[i].U()](const auto& x, const auto& u)
			{
				// ここは粒子数密度の計算なので、対ダミー粒子も含める
				const Vector dx = x - thisX;
				const Vector du = u - thisU;
				const auto r = boost::numeric::ublas::norm_2(dx);
				return boost::numeric::ublas::inner_prod(dx, du) / (r*r*r);
			});
```

* 正方格子に配置して、それぞれの速度を (u_i, v_i) = a(x_i, 0) のようにした。aは適当な係数.
* a倍して dndtがスケーリングすること、発散0の(u_i,v_i) = a(y_i,0) のような速度場ではdndtが0となることを確認.
* dndtの値自体が合わないので、確認中

2020-02-07 05:13 UTC, maru10t commented
よくわからなくなってきたので整理

考え方
* 高精度では、影響円(半径re)を単位時間あたりに通過する粒子数、という定義に立ち返り評価する
* r_e r_ij . u_ij / r_ij^3 を円内で積分すると、Gaussの定理から、表面からの流出フラックスとなる

計算したこと
* 速度場を (u,v) = (x,0) と与えた. 粒子は図のような等間隔格子(間隔l0)
* この速度場では、影響円の原点に対して、右隣粒子は速度(l0,0), 左隣粒子は速度(-l0,0) を持つ
* 高精度評価(MPS_HS)の計算結果 dn/dt / n0: -2.28361

作図
* ![particles](https://user-images.githubusercontent.com/5325357/74002178-a2f18e00-49b1-11ea-85ae-094b0a19912f.png)

2020-02-07 05:29 UTC, maru10t commented
* 粒子は影響円から出ていくので、当然 dn/dt < 0 であり、整合的

値自体の一致に対する良い手を思いつかなかったので、
影響円内に含まれる粒子数を増やして、連続的な評価と一致するように、テスト側を調節することにした。
影響半径 を十分大きく取り、十分大きな格子を用意して、壁の影響のない位置で比較する。
(具体的には、格子は30x30で、壁から5粒子以上離れた範囲)

* r_e = 5.0 l0 のとき dn/dt / n0 = -1.06789,  (理論値 -1.0)

2020-02-07 05:46 UTC, maru10t commented
(気持ち:  影響半径1.5だと評価値が2倍以上ずれていて、一瞬自明なバグかと思ったが、影響半径を広げたら収束したので安心。初期条件が等間隔格子であることの特殊性でズレているだけで、実際の流れ場では粒子配置がある程度ランダムになり、影響半径1.5でも時間平均的にはそこそこの精度を達成するのだろうなあ。と解釈した。)

速度を2次、3次関数として 同様の比較を行う。

2020-02-07 05:53 UTC, maru10t commented
1次のとき、(u,v) = (1.0 x, -0.3 z) としたとき、解析解 dn/dt /n0 = -0.7 に対して、数値解 -0.74752 (r_e = 5.0) を確認した

2020-02-07 08:01 UTC, maru10t commented
高次速度場の計算
影響半径r_e = 5 l0, (u,v) = (ax^2, bz^2) の解析値, カッコ内は解析値
相対誤差は10%に収まる。

```
dn/dt: 711.489(660)
dn/dt: 710.421(659)
dn/dt: 709.353(658)
dn/dt: 708.285(657)
dn/dt: 707.218(656)
dn/dt: 810.802(753)
dn/dt: 809.735(752)
dn/dt: 808.667(751)
dn/dt: 807.599(750)
dn/dt: 806.531(749)
dn/dt: 916.523(852)
dn/dt: 915.455(851)
dn/dt: 914.387(850)
dn/dt: 913.319(849)
dn/dt: 912.252(848)
dn/dt: 1028.65(957)
dn/dt: 1027.58(956)
dn/dt: 1026.52(955)
dn/dt: 1025.45(954)
dn/dt: 1024.38(953)
dn/dt: 1147.19(1068)
dn/dt: 1146.12(1067)
dn/dt: 1145.05(1066)
dn/dt: 1143.98(1065)
dn/dt: 1142.91(1064)
```

2020-02-07 08:25 UTC, maru10t commented
@LWisteria レビューお願いします

2020-02-09 08:04 UTC, LWisteria requested changes
@maru10t レビューしました！

2020-02-09 08:04 UTC, LWisteria commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +					auto dndt = NeighborDensityVariationSpeed(id) / p[i].N();
const?

2020-02-09 08:04 UTC, LWisteria commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +			for (auto j = decltype(num_z){wallMargin}; j < num_z - wallMargin; j++)
`wallMargin`で型が明らかなので、`decltype(num_z)`は不要だと思います（型変換したいならちゃんと`static_cast`すべき）

2020-02-09 08:04 UTC, LWisteria commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +		// (u,v) = (ax^2,bz^3) 型の、発散が -(2ax+3bz) である速度場を与える
数式の表記と実装合わせたほうがわかりやすいと思います。実装はu=-1/2ax^2になってますよね？

2020-02-09 08:04 UTC, LWisteria commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +					ASSERT_NEAR(abs((dndt - dndt_analy) / dndt_analy), 0.0, testAccuracy);
std::abs?（じゃないと整数absになっているような）

2020-02-14 05:13 UTC, maru10t commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +					auto dndt = NeighborDensityVariationSpeed(id) / p[i].N();
つけました

2020-02-14 05:14 UTC, maru10t commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +			for (auto j = decltype(num_z){wallMargin}; j < num_z - wallMargin; j++)
削除しました

2020-02-14 05:14 UTC, maru10t commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +		// (u,v) = (ax^2,bz^3) 型の、発散が -(2ax+3bz) である速度場を与える
はい、不一致でした。合わせました > 表記と実装

2020-02-14 05:14 UTC, maru10t commented on src/OpenMps/test/test_ComputerNeighborDensityVariation.cpp
> +					ASSERT_NEAR(abs((dndt - dndt_analy) / dndt_analy), 0.0, testAccuracy);
std::つけました

2020-02-14 05:15 UTC, maru10t commented
@LWisteria 修正しました

2020-02-14 06:01 UTC, LWisteria approved these changes
LGTM

2020-02-14 06:01 UTC, merged